[package]
name = "simplelink"
version = "0.1.0"
authors = ["Val Vanderschaegen <valere.vanderschaegen@gmail.com>"]

[dependencies]
byteorder = "0.5"
log = "0.3.6"
fern = "0.3.5"
time = "0.1.35"
rand = "0.3.14"

[lib]
name = "simplelink"
path = "src/lib.rs"