[package]
name = "nbplink"
version = "0.1.0"
authors = ["Val Vanderschaegen <valere.vanderschaegen@gmail.com>"]

[dependencies]
serial = "0.3"
byteorder = "0.5"
clap = "2.9.0"

[lib]
name = "nbplink"
path = "src/lib.rs"

[[bin]]
name = "nbpconsole"
path = "src/console/main.rs"