[package]
name = "api_android"
version = "0.1.0"
authors = ["Val Vanderschaegen <valere.vanderschaegen@gmail.com>"]

[dependencies]
libc = "0.2.17"
log = "0.3.6"
fern = "0.3.5"
jni = { path = "external/jni-rs" }
simplelink = { path = "../" }

[lib]
name = "slink_android"
crate-type = ["cdylib"]