[package]
name = "slink_serial"
version = "0.1.0"
authors = ["Val Vanderschaegen <valere.vanderschaegen@gmail.com>"]

[dependencies]
libc = "0.2.17"
serial = "0.3"
slink_capi = { path = "../capi" }

[lib]
name = "slink_serial"
crate-type = ["cdylib"]